# Используем только nginx
FROM nginx:alpine

# Кладём конфиг nginx
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем уже собранный билд фронтенда
COPY frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
